config/routes.rb
Rails.application.routes.draw do

  root 'products#dashboard'
  get 'products/bulk_upload'
  post 'products/bulk_upload' => 'products#create_products_in_bulk'

  get 'contracts_import/new' => 'contracts_import#new', as: :new_contracts_import
  post 'contracts_import/new' => 'contracts_import#create', as: :contracts_import

  resources :releases
  resources :products

  resources :contracts
  resources :forms

end

app/models/contract.rb
class Contract < ActiveRecord::Base
  @@contract_params_excel_import = ["contract_no", "product_id", "scenario"]
  @allowed_types = ["NB", "Reprint", "Reprocess", "Agent Duplicate"]

  validates :contract_no, presence: true, length: {minimum: 3, maximum: 10},
    uniqueness: { scope: [:scenario, :product_id],
      message: "- %{value} already exists. Contract_no, scenario and product combination should be unique" }

  validates :scenario, presence: true, inclusion: { in: @allowed_types,
    message: "%{value} is not a valid scenario, scanario can only be [NB, Reprint, Reprocess, Agent Duplicate]" }

  validates :product_id, presence: {message: "should be present. Note: If this msg is shown in during contract import, we tried to create the product with the product_name, but product could not be created"}


  before_save :populateTimeFields
  belongs_to :product
  has_and_belongs_to_many :forms, before_add: :check_uniqueness

  cattr_accessor :contract_params_excel_import

  def check_uniqueness form
    if forms.exists? form.id
      p "inside uniqueness check - if condition"
      form.errors.add(:base, "this contract-form combination already exists")
      raise ActiveRecord::Rollback
    end
    true
  end

  def changeContractNumberCase
    self.contract_no.upcase!
    true
  end

  def populateTimeFields
    if self.user_id
      self.allocated_at = DateTime.now()
    end

    true
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]

  def index
    @contracts = Contract.all
  end

  def show
  end

  def new
    @contract = Contract.new
  end

  def update
    if @contract.update(contract_params)
      redirect_to @contract, notice: 'contract was successfully updated.'
    else
      render :edit
    end
  end

  def create
    @contract = Contract.new(contract_params)
    if @contract.save
      redirect_to @contract, notice: 'contract was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
      @contract = Contract.find(params[:id])
    end

    def make_contract_upcase
      contract_params["contract_no"].upcase!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).
            permit(:contract_no, :sequence_tested, :end_to_end_tested, :scenario, :allocated_at,
            :dm_file_path, :csf_file_path, :dm_page_range, :contract_weight, :product_id, :user_id)
    end
end

app/views/contracts/_form.html.erb
<%= form_for(@contract) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contract_no %><br>
    <%= f.text_field :contract_no, required: true %>
  </div>
  <div class="field">
    <%= f.label :scenario %><br>
    <%= f.select :scenario, ["NB", "Reprint", "Reprocess", "Agent Duplicate"], required: true %>
  </div>

  <div class="field">
    <%= f.label :dm_file_path %><br>
    <%= f.text_area :dm_file_path %>
  </div>
  <div class="field">
    <%= f.label :dm_page_range %><br>
    <%= f.text_field :dm_page_range %>
  </div>
  <div class="field">
    <%= f.label :csf_file_path %><br>
    <%= f.text_area :csf_file_path %>
  </div>
  <div class="field">
    <%= f.label :sequence_tested %><br>
    <%= f.check_box :sequence_tested %>
  </div>

  <div class="field">
    <%= f.label :end_to_end_tested %><br>
    <%= f.check_box :end_to_end_tested %>
  </div>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :product_name, {prompt: true}, {required: true} %>
  </div>

  <div class="field">
    <%= f.label :user_id, "Allocated to" %><br>
    <%= f.collection_select :user_id, User.all, :id, :username, {prompt: true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing Contract</h1>


<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing Contracts</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>
        Contract ID
      </th>
      <th>Contract No</th>
      <th>Scenario</th>
      <th>Product Name</th>
      <th>Forms Covered</th>
      <th>Sequence Tested?</th>
      <th>End to End Tested?</th>
      <th>Allocated At</th>
  </thead>

  <tbody>
    <% @contracts.each do |contract| %>
      <tr>
        <td><%= link_to contract.id, contract %></td>
        <td><%= contract.contract_no %></td>
        <td><%= contract.scenario %></td>
        <td><%= contract.product.product_name if contract.product %></td>
        <td><%= contract.forms.size %></td>
        <td><%= contract.sequence_tested ? "Yes" : "No" %></td>
        <td><%= contract.end_to_end_tested ? "Yes" : "No" %></td>

        <td><%= contract.allocated_at %></td>

        <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contract', new_contract_path %>
<%= link_to 'Import Contract', new_contracts_import_path %>

app/views/contracts/new.html.erb
<h1>New Contract</h1>
<%= render 'form' %>
<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<h1>Showing Contract</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Contract No </strong>
  <%= @contract.contract_no %>
</p>

<p>
  <strong>Scenario</strong>
  <%= @contract.scenario %>
</p>
<p>
  <strong>DM File Path</strong>
  <%= @contract.dm_file_path %>
</p>
<p>
  <strong>DM Page Range</strong>
  <%= @contract.dm_page_range %>
</p>
<p>
  <strong>CSF File Path</strong>
  <%= @contract.csf_file_path %>
</p>
<p>
  <strong>Sequence Tested?</strong>
  <%= @contract.sequence_tested ? "Yes": "Not Yet" %>
</p>

<p>
  <strong>End to End Tested?</strong>
  <%= @contract.end_to_end_tested ? "Yes": "Not Yet" %>
</p>

<p>
  <strong>Allocated at</strong>
  <%= @contract.allocated_at %>
</p>


<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>