config/routes.rb
Rails.application.routes.draw do

  root 'products#dashboard'
  get 'products/bulk_upload'
  post 'products/bulk_upload' => 'products#create_products_in_bulk'

  get 'contracts_import/new' => 'contracts_import#new', as: :new_contracts_import
  post 'contracts_import/new' => 'contracts_import#create', as: :contracts_import

  resources :releases
  resources :products

  resources :contracts
  resources :forms

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :edit, :update, :destroy]
  before_action :make_name_upcase, only: [:create, :update]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create

    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to @form, notice: 'form was successfully created.' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update

    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to @form, notice: 'form was successfully updated.' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json

  def destroy
      @form.destroy
      respond_to do |format|
        format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
        format.json { head :no_content }
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    def make_name_upcase
      form_params["form_name"].upcase!
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form)
      .permit(
        :form_name, :actual_drop_date, :released, :story_card_validated,
        :executed_with, :form_status, :form_exec_status, :comments, :product_id
        )
    end
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :form_name %><br>
    <%= f.text_field :form_name, required: true %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.collection_select :product_id, Product.all, :id, :product_name, {prompt: true}, {required: true} %>
  </div>
  <div class="field">
    <%= f.label :actual_drop_date %><br>
    <%= f.date_field :actual_drop_date %>
  </div>
  <div class="field">
    <%= f.label :released %><br>
    <%= f.check_box :released %>
  </div>
  <div class="field">
    <%= f.label :story_card_validated %><br>
    <%= f.check_box :story_card_validated %>
  </div>
  <div class="field">
    <%= f.label :form_status %><br>
    <%= f.select :form_status, ["Triggered", "EDL Missing", "Out Of Scope", "Print Solution", "Untriggered", "Mock"], prompt: true %>
  </div>
  <div class="field">
    <%= f.label :form_exec_status %><br>
    <%= f.select :form_exec_status, ["Yet to start","Can start","Completed"] %>
  </div>
  <div class="field">
    <%= f.label :executed_with %><br>
    <%= f.select :executed_with, ["Mock", "EDL Dump", "Contract", "EDL Dump/Contract"], {prompt: true},
    {disabled: true}  %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>

  <div class="actions">
    <%= f.submit(:data => {:disable_with => "Please wait.."}) %>
    <%= f.submit "Clear/Undo", :type => "reset" %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Forms</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Form Name</th>
      <th>Product</th>
      <th>Form Status</th>
      <th>Released?</th>
      <th>Drop Date</th>
      <th>Form Execution Status</th>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.form_name %></td>
        <td><%= form.product_id.nil? ? "" : form.product.product_name %></td>
        <td><%= form.form_status %></td>
        <td><%= form.released ? "Yes" : "No" %></td>
        <td><%= form.actual_drop_date %></td>
        <td><%= form.form_exec_status %></td>
        <td><%= link_to 'Show', form %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
        <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Form Name</strong>
  <%= @form.form_name %>
</p>

<p>
  <strong>Released?</strong>
  <%= @form.released ? "Yes": "Not Yet" %>
</p>
<p>
  <strong>Story Card Validated?</strong>
  <%= @form.story_card_validated ? "Yes" : "Not Yet" %>
</p>
<p>
  <strong>Form Status</strong>
  <%= @form.form_status%>
</p>
<p>
  <strong>Form Execution Status</strong>
  <%= @form.form_exec_status %>
</p>
<p>
  <strong>Form Executed With:</strong>
  <%= @form.executed_with %>
</p>
<p>
  <strong>Comments:</strong>
  <%= @form.comments %>
</p>

<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>