config/routes.rb
Rails.application.routes.draw do

  root 'products#dashboard'
  get 'products/bulk_upload'
  post 'products/bulk_upload' => 'products#create_products_in_bulk'

  get 'contracts_import/new' => 'contracts_import#new', as: :new_contracts_import
  post 'contracts_import/new' => 'contracts_import#create', as: :contracts_import

  resources :releases
  resources :products

  resources :contracts
  resources :forms

end

app/controllers/contracts_import_controller.rb
class ContractsImportController < ApplicationController
  def new
    @contract_import = ContractImport.new
  end

  def create
    @contract_import = ContractImport.new(params[:contract_import])
    if @contract_import.save
      redirect_to contracts_path, notice: "Contracts imported successfully.!"
    else
      render :new
    end
  end

end

app/views/contracts_import/new.html.erb
<h2>Import Contracts</h2>
<p>
  <b>Fields Accepted</b>
  <ul>
    <li> <b>contract_no</b> - string and mandatory field
    <li> <b>scenario</b> - string and mandatory field, should be NB/Reprint/Reprocess/Agent Duplicate
    <li> <b>product_name</b> - string and mandatory
    <li> <b>form_name</b> - string and mandatory
  </ul>
</p>
<p>
  Note:
  <b>
    <ul>
       <li>Please make sure the header row has field names as mentioned above
  </b>
</p>

<%= form_for @contract_import, url: contracts_import_path do |f| %>
  <% if @contract_import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract_import.errors.count, "error") %> prohibited this import from completing:</h2>
      <ul>
      <% @contract_import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :file, required: true %>
  </div>
  <div class="buttons"><%= f.submit "Import" %></div>
<% end %>

<p>
  <%= link_to 'Contracts Page', contracts_path %>
</p>