config/routes.rb
Rails.application.routes.draw do

  root 'products#dashboard'
  get 'products/bulk_upload'
  post 'products/bulk_upload' => 'products#create_products_in_bulk'

  get 'contracts_import/new' => 'contracts_import#new', as: :new_contracts_import
  post 'contracts_import/new' => 'contracts_import#create', as: :contracts_import

  resources :releases
  resources :products

  resources :contracts
  resources :forms

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :product_name, presence: true, length: {minimum: 3, maximum: 15}, uniqueness: true
  belongs_to :release
  has_many :forms
  before_validation :upcase_fields

  def upcase_fields
    self.product_name.upcase!
    self.lob.upcase! if !self.lob.nil?
    true
  end
end

app/controllers/products_controller.rb
require_relative "bulk_uploader"
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :make_name_upcase, only: [:create, :update]

  def dashboard
    @release = Release.find_by(current: true)
    @products = @release.products.where.not(product_status: "Out of Scope")
  end
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def fetch_products_based_on_release
    @products = Release.find(params[:id]).products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bulk_upload
  end

  def create_products_in_bulk

    puts params[:file_name]
    obj = BulkUploader.new(params[:file_name])
    records = obj.call(params[:output_file_path])
    redirect_to products_url, notice: "#{records} product(s) created successfully"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def make_name_upcase
      product_params["product_name"].upcase!
      if !(product_params["lob"].nil?)
        product_params["lob"].upcase!
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).
        permit(:product_name, :planned_drop_date, :mapped_or_product_with_zero_forms,
        :lob, :release_id, :rtc_task_updated)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name, required: true %>
  </div>
  <div class="field">
    <%= f.label :planned_drop_date %><br>
    <%= f.date_field :planned_drop_date %>
  </div>
  <div class="field">
    <%= f.label :mapped_or_product_with_zero_forms, "Mapped Product/Product With 0 Forms" %><br>
    <%= f.check_box :mapped_or_product_with_zero_forms %>
  </div>
  <div class="field">
    <%= f.label :lob %><br>
    <%= f.select :lob, ["PALLM", "Cyberlife", "ICUBE", "Vision"], {prompt: true}, {required: true} %>
  </div>
  <div class="field">
    <%= f.label :product_status %><br>
    <%= f.select :product_status, ["", "Out of Scope"], {prompt: true} %>
  </div>
  <div class="field">
    <%= f.label :release_id %><br>
    <!-- <%= f.text_field :release_id %> -->
    <%= f.collection_select :release_id, Release.all, :id, :name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :rtc_task_updated, "RTC Task Updated" %><br>
    <%= f.check_box :rtc_task_updated %>
  </div>
  <div class="actions">
    <%= f.submit(:data => {:disable_with => "Please wait.."}) %>
    <%= f.submit "Clear/Undo", :type => "reset" %>
  </div>
<% end %>

app/views/products/bulk_upload.erb
<h1>Bulk Uploader </h1>
<%= form_tag(action: "bulk_upload", multipart: true) do %>

  <%= file_field_tag(:file_name, required: true) %>
  <br><br>
  <%= label_tag(:output_file_path, "Output File Path") %>
  <%= text_area_tag(:output_file_path, "", size: "40x2") %>
  <br><br>
  <%= submit_tag("BulkUpload") %>

<% end %>

app/views/products/dashboard.html.erb
<div>
  <p>
    <h1>Dashboard for release - <%= @release.name %></h1>
  </p>
</div>
<%

  total_forms = 0
  edl_missing_forms = 0
  total_exec_forms = 0
  completed_products = 0
  @products.each do |product|
    total_forms += product.forms.where.not(form_status: "Out Of Scope").count
    edl_missing_forms += product.forms.where(form_status: "EDL Missing").count
    total_exec_forms += product.forms.where(form_exec_status: "Completed").count
    completed_products += 1 if (product.forms.size == product.forms.where(form_exec_status: "Completed") && nodefects)
  end


%>

<div>
  <p>
    <h3>Overall Execution Status</h3>
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>Total forms</th>
          <th>EDL Missing</th>
          <th>Total Executed Forms</th>
          <th>100% Completed Products</th>
        </thead>
        <tbody>
          <tr>
            <td><%= total_forms %></td>
            <td><%= edl_missing_forms %></td>
            <td><%= total_exec_forms %></td>
            <td><%= completed_products %></td>
          </tr>
        </tbody>
      </table>
  </p>
</div>



<div>
  <p>
    <h3>Execution Status</h3>
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>LOB</th>
          <th>EDL Missing</th>
          <th>Forms released - Expected</th>
          <th>Forms released - Actual</th>
          <th>TD - Contract Available Forms</th>
          <th>TD - Mock Forms</th>
          <th>TD - Not Available</th>
          <th>Execution completed - Contract</th>
          <th>Execution completed - Mock</th>
          <th>Execution pending</th>
        </thead>
        <tbody>
          <%
            @products.select(:lob).distinct.each do |product|
              next if product.lob.blank?
          %>
          <tr>
            <td> <%= current_lob = product.lob %> </td>
            <%
              forms_count_lob = 0
              edl_missing_forms_lob = 0
              forms_released_count_lob = 0
              td_available_contracts_released_forms = 0
              td_available_mock_released_forms = 0
              lob_products = @products.where("lob = ? and planned_drop_date < ?", current_lob, Date.today)
              lob_products.each do |lob_product|
                forms_count_lob += lob_product.forms.where.not(form_status: "Out of Scope").count
                edl_missing_forms_lob += lob_product.forms.where(form_status: "EDL Missing").count

                forms_released_count_lob += lob_product.forms.where(released: true).
                  where.not(form_status: ["EDL Missing", "Out of Scope"] ).count

                all_forms_lob_product = lob_product.forms
                all_forms_lob_product.each do |current_form|
                  if current_form.released
                    if current_form.form_status.eql? "Triggered" && current_form.contracts.exists?
                      td_available_contracts_released_forms += 1
                    elsif current_form.form_status.eql? "Mock"
                      td_available_mock_released_forms += 1
                    end

                  end
                end

              end
            %>
            <td><%= edl_missing_forms_lob %></td>
            <td><%= forms_count_lob %></td>
            <td><%= forms_released_count_lob %></td>
            <td><%= td_available_contracts_released_forms %></td>
            <td><%= td_available_mock_released_forms %></td>
            <td><%= forms_released_count_lob - td_available_contracts_released_forms - td_available_mock_released_forms %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
  </p>
</div>


<div>
  <p>
    <h3>Test Data Status</h3>
    <table class="table table-striped table-bordered table-condensed">
      <thead>
        <tr>
          <th>LOB</th>
          <th>Total forms</th>
          <th>EDL Missing</th>
          <th>Total Testdata Available Forms</th>
          <th>Contract Available Forms - released</th>
          <th>Mock Forms - released</th>
          <th>Pending Forms - released</th>
        </thead>
        <tbody>
          <tr></tr>
        </tbody>
      </table>
  </p>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
 <%= link_to 'Back', products_path %>

app/views/products/fetch_products_based_on_release.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Planned Drop Date</th>
      <th>Mapped/ProductWith0Forms</th>
      <th>LOB</th>
      <th>Release</th>
      <th>RTC Task Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.planned_drop_date %></td>
        <td><%= product.mapped_or_product_with_zero_forms ? "Mapped" : "" %></td>
        <td><%= product.lob %></td>
        <td><%= product.release_id.nil? ? "" : product.release.name  %></td>
        <td><%= product.rtc_task_updated ? "Yes" : "No"  %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %> |
<%= link_to 'Bulk Upload', products_bulk_upload_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table table-striped table-bordered table-condensed">
  <thead>
    <tr>
      <th>Product name</th>
      <th>Planned Drop Date</th>
      <th>Mapped/ProductWith0Forms</th>
      <th>LOB</th>
      <th>Release</th>
      <th>RTC Task Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.planned_drop_date %></td>
        <td><%= product.mapped_or_product_with_zero_forms ? "Mapped" : "" %></td>
        <td><%= product.lob %></td>
        <td><%= product.release.name if product.release  %></td>
        <td><%= product.rtc_task_updated ? "Yes" : "No"  %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %> |
<%= link_to 'Bulk Upload', products_bulk_upload_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Planned Drop Date:</strong>
  <%= @product.planned_drop_date %>
</p>

<p>
  <strong>Mapped Product/Product With 0 Forms:</strong>
  <%= @product.mapped_or_product_with_zero_forms ? "TRUE" : "FALSE" %>
</p>

<p>
  <strong>LOB:</strong>
  <%= @product.lob %>
</p>

<p>
  <strong>Product status:</strong>
  <%= @product.product_status if @product.product_status %>
</p>

<p>
  <strong>Release:</strong>
  <%= @product.release.nil? ? "Not Selected" : @product.release.name %>
</p>

<p>
  <strong>RTC Task Updated:</strong>
  <%= @product.rtc_task_updated ? "Yes" : "No" %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', :back %>